subo primera parte de la tarea 3
sergio-ceballos-intelex/tareas-modulo-3-grupo-11 pull request #14
Opened 2024-09-07 00:44 UTC by Giovanych

Creo un archivo .js y desarrollé un script que muestra en consola los números del 1 al 50.

2024-09-07 01:54 UTC, Giovanych commented
![Uploading Captura de pantalla 2024-09-06 205149.png…]()

2024-09-09 00:23 UTC, sergio-ceballos-intelex requested changes
te falta la captura de pantalla en la descripcion del PR del historial, es decir el comando que esta especificado en la tarea

2024-09-11 18:22 UTC, Giovanych commented
profe la captura la deje en un comentario

2024-09-13 03:41 UTC, sergio-ceballos-intelex approved these changes

2024-09-13 03:41 UTC, merged